# Generated by Django 5.2.5 on 2025-09-03 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('action', models.CharField(max_length=255)),
                ('is_pleasant', models.BooleanField(default=False)),
                ('periodicity', models.PositiveSmallIntegerField(default=1)),
                ('reward', models.CharField(blank=True, max_length=255, null=True)),
                ('duration_seconds', models.PositiveSmallIntegerField()),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_habit', models.ForeignKey(blank=True, limit_choices_to={'is_pleasant': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pleasant_related', to='habits.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
